/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 banana.glb --transform 
Files: banana.glb [7.95MB] > C:\Users\USER\code-canvas-3\public\banana-transformed.glb [35.9KB] (100%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/banana-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Banana.geometry} material={materials.Banana_High} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/banana-transformed.glb')
